# Manual de instruções para o GitHub
name: Enviar site para Azure

# Gatilho: Rodar sempre que houver atualização na branch 'main'
on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest # Usar uma máquina virtual limpa

    steps:
      # Passo 1: Baixar o código do seu GitHub
      - name: 'Baixar o código'
        uses: actions/checkout@v4

      # Passo 2: Preparar o ambiente PHP
      - name: 'Preparar PHP 8.2'
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.4'

      # Passo 3: Preparar o Node.js para os arquivos de estilo (CSS)
      - name: 'Preparar Node.js'
        uses: actions/setup-node@v3
        with:
          node-version: '22'

      # Passo 4: Instalar as dependências do Laravel
      - name: 'Instalar pacotes do Composer'
        run: composer install --prefer-dist --no-progress --no-dev -o

      # Passo 5: Instalar pacotes do front-end
      - name: 'Instalar pacotes do NPM'
        run: npm install

      # Passo 6: Compilar os arquivos de estilo e script
      - name: 'Compilar CSS e JS'
        run: npm run build

      # Passo 7: Usar o crachá para fazer login na Azure
      - name: 'Fazer login na Azure'
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      # Passo 8: Enviar os arquivos do site para a "casa" na Azure
      - name: 'Enviar arquivos para o App Service'
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'Gestão Financeira' # <<< TROQUE AQUI pelo nome do seu App Service
          package: .
